FORMAT: 1A

# Behalf API v3
Behalf's API aims to expose all available functionality to an authenticated client.

Using this API, a remote system can create new users, approve customers for loans and generate referred payments. In this reference you can find information about the actions Behalf exposes and the data resources the API returns as responses to these requests.

#Standard URL structure
Behalf’s API uses the https scheme only. Requests in http will be completely ignored.

Behalf API requests rely on REST verbs to perform actions or to retrieve information.
Read actions are performed using the GET action and associated query part of the URL.

    GET /v3/leads/<leadid>

Resource creation is done using the POST action. Parameters are passed in the request body.

    POST /v3/leads
    {"email": <lead email>}

Resource modification is done using the PUT action. Parameters are passed in the request body.

    PUT /v3/leads/<leadid>
    {"email": <lead email>}

Some resources’ properties can be modified directly. Note that some patch commands may refer to elements which are not actually properties.

    PATCH /v3/leads/<leadid>
    {"email": <lead email>}


Resource removal is done using the DELETE action. Parameters are passed in the query part of the URL. Note that PUT requests will expect an ‘id’ value to be present in the body. This id name may change for different requests.

    DELETE /v3/leads/<leadid>

#Required headers
The Behalf API strictly requires several headers to be sent in order to perform authentication and identify legitimate requests. All requests must include the following headers:

**User-Agent**: Contains a string describing the current agent performing the request. This header is used for statistical purposes to indicate browser popularity for continued support

**X-Behalf-Signature**: An authentication signature used for authentication. More details in the authentication section

**Accept**: The client should specify the desired response format. For now, only application/json is supported.

**Content-Type**: *POST*, *PATCH* and *PUT* requests must also specify the body’s format as application/json

#Request parameters
Parameters used to pass information for requests are strictly defined for their contents. Requests to the API failing to provide legal values are rejected outright.

#Response structure
Standard response structure will include the following header:

    Content-Type: application/json

##Data Types
The body will include a JSON encoded object of the resource requested.
The JSON structure returned is limited to primitives (boolean, number, string) and compounds (array, objects, null).

Dates and DateTime elements are explicitly expected to be formatted in ISO8601.

DateTime elements accept a timezone in input but will always return a UTC formatted ISO8601 string.

##Response Codes
Response codes indicate the way the requested action was handled:

**200**: OK - the action was executed and completed

**201**: Created - standard response to a POST action which also indicates that resource creation is also completed

**202**: Accepted - The action is queued and will be executed. The http status message will include the queue ID of the action. 

Errors are indicated by http response code along with a corresponding human readable message. Additional details will be attached as a JSON encoded resource structure.

Standard errors are:

**400**: Parameter validation failed
            
**401**: Authentication required or failed

    {
        "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html",
        "title": "Unauthorized",
        "status": 401,
        "detail": "Unauthorized"
    }
    
**403**: Requested resource is not available for the currently authenticated user

**404**: Resource not found

**405**: Method not allowed

**422**: Unprocessable Entity due to input validation error

    {
        "validation_messages": {
            "companyDetails": {
                "name": {
                    "stringLengthTooLong": "The input is more than 25 characters long"
                }
            }
        },
        "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html",
        "title": "Unprocessable Entity",
        "status": 422,
        "detail": "Failed Validation"
    }

**500**: Resource action failed due to internal error

**503**: Resource is currently unavailable due to maintenance or overloading

**530**: Resource is currently unavailable, try again later. This response code will have a Retry-After header to suggest an estimated retry time

Specific application errors are returned as 500 errors in the range 530 - 580

## Hypermedia links

The Behalf API v3 supports Hypermedia links as part of its standard response structure. For more information about Hypermedia links: http://en.wikipedia.org/wiki/HATEOAS.

For Behalf API consumers, the Hypermedia links that are provided indicate the next available steps for the current resource. Based on these links, a developer or an automated process can explore the API or get indications for the next steps in the current workflow.
This next step is described as a hyperlink URL which represents a resource. This resource can be called using http verbs normally. Note that many of our actions respond only to specific verbs. An invalid method error (405) will be returned if a specific verb is unavailable.

Example:

    "_links": {
        "self": {
            "href": "https://behalf.com/api/account/account-id"
        },
        "terms": {
            "href": "https://behalf.com/api/account/account-id/terms"
        },
        "customer-sales": {
            "href": "https://behalf.com/api/customer-sales-info/link-id"
        }
    }

#Authentication
The X-Behalf-Signature header contains a credentials identifier and a credentials signature. The identifier is a constant ID generated for the user. This ID is not secret. The signature, however, is a hash generated by the client for authentication.

##Obtaining or revoking public and private keys

Public and Private keys for communicating with Behalf can be obtained through our Customer Support service. Only certified merchants and verified customers may obtain keys for integration.

Keys are provided as requested and only a single pair for every single user.

##Using private keys for request signing
The credentials signature is based on the User Agent header, URL path, the request body (empty string if none is present) and the query parameters.

These strings are concatenated to each other in a particular order. The credentials' secret keys is used to sign the string we created.

The process of creating the signature starts with serializing the request data into a string in a consistent manner:

    <User-Agent><url path><request-body-json | empty string><un-formatted-request-query-parameters | empty string>

The generated string is then fed into a sha256 hmac function, keyed by the secret key. The resulting hash is sent in the signature header.

#Signature generation example
**URL**: https://beta.behalf.com/api/v1/lead/my-lead-id

With the key pair

    public my-public-key
    private my-private-key

**User-Agent**: “Testing”

The concatenated string is:

    "Testing/api/v1/lead/my-lead-id"

The private key for signing is “my-private-key”

Run (in php online functions e.g. http://mhash.onlinephpfunctions.com/):

    echo bin2hex(mhash( MHASH_SHA256, "Testing/api/v1/lead/my-lead-id", "my-private-key"));

The result is:

    f8bd1e5925e00ed709d66e1ff6fd49949836977d124a21de3e19f887896fdd72

The X-Behalf-Signature header is

    X-Behalf-Signature: my-public-key;f8bd1e5925e00ed709d66e1ff6fd49949836977d124a21de3e19f887896fdd72

#Versioning
The Behalf API supports a soft versioning policy which provides for changes in behavior, input and output options. Soft versioning means that output and input may be modified as long as it keeps backwards compatibility by not modifying or removing existing elements. Behalf is allowed to add new optional parameters or new output elements without changing the version of the API.

Any modification of input, output or behavior of an existing (and deployed) API must be done on a new version and allow for an essentially different API to replace the old one in the new version. Naturally, the old version must continue to work and keep to its previous behavior regardless of changes to any other version, higher or lower.

Version negotiation is done through the URL path and is required to be specified. An unknown or unsupported version will be rejected outright.

# Group Members
## Account Resource [/api/account]
System Account resource describing a single set of credentials and associated Company. This resource is available to authenticated users for posting.

### Create or Add data to an Account [POST]
This action creates a new Account resource or adds missing information to an existing one. It cannot be used to override existing information.
Additionally, this action creates a link between the currently authenticated user and the account.
A POST to /account can get two affirmative responses - 200 or 201.

**The 201 response** indicates the resource was created successfully and the requesting user is linked to the newly created account.

**The 200 response** indicates the resource already existed and the requesting user is now linked to the account.

In either case, the same resource is returned. An existing resource will be updated with new information only if that information is missing from the resource. An existing property will not be overridden by a POST.
+ Request Mandatory parameters only (application/json)

    + Body

            {
                "firstName": "firstname",
                "lastName":  "lastname",
                "contact": {"email":"email"},
                "companyDetails": {"name": "company name"}
            }
    
    + Schema
    
            {
                "type": "object",
                "required": true,
                "properties": {
                    "firstName": {
                        "type": "string",
                        "required": true
                    },
                    "lastName": {
                        "type": "string",
                        "required": true
                    },
                    "contact": {
                        "type": "object",
                        "required": true,
                        "properties": {
                            "email": {
                                "type": "string",
                                "required": true
                            }
                        }
                    },
                    "companyDetails": {
                        "type": "object",
                        "required": true,
                        "properties": {
                            "name": {
                                "type": "string",
                                "required": true
                            }
                        }
                    }
                }
            }
        
+ Request All available parameters (application/json)

        {
            "firstName": "firstname",
            "lastName":  "lastname",
            "contact": {"email":"email"},
            "companyDetails": {
                "name": "company name",
                "duns": "DUNS number",
                "tin": "TIN code",
                "website": "http://website.com",
                "inceptionDate": "2002-12-25" //Also accepts unix timestamp
            },
            "ssn": "123456781",
            "businessAddress": {
                "streetAddress": "",
                "zipcode": "",
                "apt-unit": "",
                "phone": ""
            },
            "personalAddress": {
                "streetAddress": "",
                "zipcode": "",
                "apt-unit": "",
                "phone": ""
            }
        }

+ Response 200 (application/json)
    
    + Body
    
            {
                "accountId": "account-id",
                "firstName": "firstname",
                "lastName": "lastname",
                "contact":{
                    "contactId": "contact-id", "email":"email"
                },
                "companyDetails": {
                    "name": "company name",
                },
                "_links": {
                    "self": {
                        "href": "https://behalf.com/api/account/account-id"
                    },
                    "terms": {
                        "href": "https://behalf.com/api/account/account-id/terms"
                    },
                    "customer-sales": {
                        "href": "https://behalf.com/api/customer-sales-info/link-id"
                    }
                }
            }

+ Response 201 (application/json)

    + Body
    
            {
                "accountId": "account-id",
                "firstName": "firstname",
                "lastName": "lastname",
                "contact":{
                    "contactId": "contact-id", "email":"email"
                },
                "companyDetails": {
                    "name": "company name",
                },
                "_links": {
                    "self": {
                        "href": "https://behalf.com/api/account/account-id"
                    },
                    "terms": {
                        "href": "https://behalf.com/api/account/account-id/terms"
                    },
                    "customer-sales": {
                        "href": "https://behalf.com/api/customer-sales-info/link-id"
                    }
                }
            }

## Account Terms [/api/account/{accountId}/terms?vendor={vendorId}]
Account subresource that describes the account's available terms. This resource is only available to authenticated linked users or to the owner of the account.
+ Parameters
    + accountId (required, string, `BHae12d442123`) ... Unique identifier of the /account resource
    + vendor (optional, string, `BHae12d442123`) ... Unique identifier of the vendor to cross terms with

### Retrieve account terms [GET]
Retrieve a terms resource for the requested account. This action may cause terms to be recalcualted for the account.
If a vendor is specified, the terms are provided for an expected transaction between the customer's account and the specified vendor.
+ Response 200 (application/json)

        {
            "line": 5000,
            "balance": 4500,
            "maxRepayment": 60,
            "feePer1K": 20,
            "grace": null,
            "minAmount": 300,
            "maxAmount": 5000,
            "repaymentsFrequency": "Monthly|Daily"
        }
        
+ Response 400 (application/json)
    
    "Account is missing properties" followed by a list of missing properties. This list details those /account resource properties which have no value and must be entered to retrieve Terms.
    
    Entering new values into /account properties is done by POST to /account with the terms accountId.

    + Body
    
            {
                "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html",
                "title": "Bad Request",
                "status": 400,
                "detail": "Account is missing properties: ssn"
            }

## Customer Sales Info [/api/customer-sales-info/{linkId}]
A resource that describes the connection between a particular customer and a particular vendor. This resource provides historical information about the customer, from the vendor's point of view.
The linkId parameter is returned as part of the POST /api/account action
+ Parameters
    + linkId (required, string, `BHae12d442123`) ... Unique identifier of the /links resource

### Retrieve a link by linkId [GET]

+ Response 200 (application/json)

    + Body

            {
                "linkId": "BHae12d442123",
                "vendorId": "BHae12d442123",
                "customerId": "BHae12d442123",
                "knownSince": "2002-12-25",
                "totalSalesAmount": 1000,
                "totalSalesCount": 355,
                "ytdSalesAmount": 45,
                "ytdSalesCount": 12,
                "avgYtdSalesAmount": 32,
                "paymentMethod": "COD"
            }
            
### Update link properties [PUT]

+ Request (application/json)

    + Body

            {
                "knownSince": "2002-12-25",
                "totalSalesAmount": 1000,
                "totalSalesCount": 355,
                "ytdSalesAmount": 45,
                "ytdSalesCount": 12,
                "avgYtdSalesAmount": 32,
                "paymentMethod": "COD"
            }

+ Response 200 (application/json)

    + Body

            {
                "linkId": "BHae12d442123",
                "vendorId": "BHae12d442123",
                "customerId": "BHae12d442123",
                "knownSince": "2002-12-25",
                "totalSalesAmount": 1000,
                "totalSalesCount": 355,
                "ytdSalesAmount": 45,
                "ytdSalesCount": 12,
                "avgYtdSalesAmount": 32,
                "paymentMethod": "COD"
            }